language: java
jdk: openjdk9

env:
  global:
    - COVERAGE=0.3
  jobs:
    - COVERAGE=0.05 FEATURE=ui
    - COVERAGE=0.15 FEATURE=service/cart
    - COVERAGE=0.05 FEATURE=service/user
    - COVERAGE=0.4 FEATURE=repository/order
    - COVERAGE=0.05 FEATURE=repository/cart
    - COVERAGE=0.15 FEATURE=repository/product
    - COVERAGE=0.34 FEATURE=repository/user


install:
  - ./gradlew clean jar

script:
  - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$FEATURE check

after_success:
  - find . -name jacocoTestReport.csv | xargs cat | awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true
