language: java
jdk:
- openjdk9
- oraclejdk9

services:
  - docker

env:
  global:
  - COVERAGE=0.3
  - secure: NAuJsitk587YiEt/cdg0eLWTXp2Tpgb5dcYjdenibOKXcl02NAdk1WWXeXlraKnJbZ7Kna61gXXQpBhEkZSyOwnZinjKTQoCf63RJ6npzxVprBC2A5kL9jfSP8jaxT+s4wncPvrYsgTfTRnJ2gNK7e+CjEOuAF4UxIloO61Oy9bGl+y25/oL13VT7b8PYEy3Wvgd82hxQIMWoE2YAu7P0kFC1U2kvmKw/ieJ1K8liMHk7Ce3uY0JwAN5Ui6YflUAB81hrqgHk9tvK4p9+z2WW/1+4Zu3LcNJl0Blkvy7rYS15FdfiSeVfqZF6aFTvm4Kf1S9aai5VSsM4zZclXY9cMVfYTPkKQIrLDPi+NMrKbCz0Omw22E/3+Rb25KFLqOYLBYxzgoFmJDK46AO1sxoLqM1/55p9CW0ecR7PpYiYCeKqtJFhTcSFicwSDIS4dc+e6EOGGVkXkKfwrFtgw+pW0nG0wNGYik+22vGmARoKkAY9L1mDYtbeWWsMDTupo4eTyWaLngI7S3nucJzRVvieQUP74m2t+JB+zYGNTtmdLfKC7+La+3N8uY0NjkTm87vL9jaNig+kbUihi/eV7ozvP9Ld4e1qeMIp49y2rH1rbdrRQN7+F1qnwbFN64Y5sYQA+TGQW0x4a6s3oCvwsHPhe2AYDRWL6O/wOyoCNhfdL8=
  jobs:
  - COVERAGE=0.05 FEATURE=ui
  - COVERAGE=0.1 FEATURE=service/cart
  - COVERAGE=0 FEATURE=service/user
  - COVERAGE=0.35 FEATURE=repository/order
  - COVERAGE=0 FEATURE=repository/cart
  - COVERAGE=0.1 FEATURE=repository/product
  - COVERAGE=0.3 FEATURE=repository/user

install:
- "./gradlew clean jar"

script:
- COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$FEATURE check

after_success:
- find . -name jacocoTestReport.csv | xargs cat | awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script:
    - echo 'WIP'
    - bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\" --password-stdin"
  on:
    all_branches: true
