language: java
jdk: openjdk9

env:
  global:
    - COVERAGE=0.3

install:
  - ./gradlew clean jar

script:
  - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/ui check
  - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/service/cart check
  - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/service/user check

  - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/order check
  - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/cart check
  - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/product check
  - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/user check

after_success:
  - find . -name jacocoTestReport.csv | xargs cat | awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true
