language: java
jdk: openjdk9

env:
  - COVERAGE = 0.3

install:
  - ./gradlew clean jar

script:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv | xargs cat | awk -F',' '{print $3" "$4" "$5}'

before_deploy:
  - COVERAGE=$(COVERAGE) ./gradlew test jacocoTestCoverageVerification

deploy:
  provider: script
  script: deploy.sh
  on:
    all_branches: true
